# CodegenAPI Task Configuration

# Task type mappings - each task type maps to a template file
tasks:
  PLAN_CREATION: TASKS/PLAN_CREATION.md
  CODE_RESTRUCTURE: TASKS/CODE_RESTRUCTURE.md
  FEATURE_IMPLEMENTATION: TASKS/FEATURE_IMPLEMENTATION.md
  BUG_FIX: TASKS/BUG_FIX.md
  CODEBASE_ANALYSIS: TASKS/CODEBASE_ANALYSIS.md
  TEST_GENERATION: TASKS/TEST_GENERATION.md

# API configuration
api:
  base_url: https://codegen-sh-rest-api.modal.run
  timeout: 300

# Local storage configuration
storage:
  tasks_dir: ~/.codegenapi/tasks
  logs_dir: ~/.codegenapi/logs

# Default settings
defaults:
  retry_count: 3
  log_level: INFO

