[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E402"]  # Ignore module level import not at top of file

[tool.ruff.lint.per-file-ignores]
"mcp/server.py" = ["F401"]  # Ignore unused import in server.py
"mcp/test_*.py" = ["E402"]  # Ignore import order in test files

[tool.ruff.lint.isort]
known-first-party = ["mcp"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
follow_imports = "silent"

[tool.mypy.overrides]
module = "mcp.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

