[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E402"]  # Ignore module level import not at top of file

[tool.ruff.lint.isort]
known-first-party = ["mcp"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = "mcp.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

