# Default Codegen CLI Configuration
# This file contains the default configuration values for the CLI

# API Configuration
api:
  base_url: "https://api.codegen.com"
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  # token: ""  # Set via environment variable or config command
  # org_id: 0  # Set via environment variable or config command

# Output Configuration
output:
  format: "table"  # Options: table, json, yaml, text
  color: true
  pager: true

# CLI Behavior
cli:
  confirm_destructive: true
  progress_bars: true
  auto_update_check: true

# Logging Configuration
log:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # file: null  # Optional log file path
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
